spring:
  application:
    name: movie-rating-system
  
  # Database Configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/movie_rating_system
    username: postgres
    password: password
  
  # Flyway Configuration
  flyway:
    url: jdbc:postgresql://localhost:5432/movie_rating_system
    user: postgres
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging Configuration
logging:
  level:
    org.flywaydb: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
